[package]
name = "taffy"
version = "0.2.0"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
description = "A flexible UI layout library"
repository = "https://github.com/DioxusLabs/taffy"
keywords = ["cross-platform", "layout", "flexbox"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
hash32 = "0.2"
hash32-derive = "0.1"
num-traits = { version = "0.2", default-features = false }
typenum = "1"
hashbrown = { version = "0.12", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }
slotmap = "1.0.6"

[features]
default = ["std"]
alloc = ["hashbrown"]
std = ["num-traits/std"]
serde = ["dep:serde"]

[dev-dependencies]
criterion = "0.3"
rstest = "0.16.0"

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "generated"
path = "benches/generated/mod.rs"
harness = false

[[bench]]
name = "complex"
path = "benches/complex.rs"
harness = false

[workspace]
members = ["scripts/gentest"]
