[package]
name = "taffy"
version = "0.3.0-alpha1"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "A flexible UI layout library"
repository = "https://github.com/DioxusLabs/taffy"
keywords = ["cross-platform", "layout", "flexbox"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
num-traits = { version = "0.2", default-features = false }
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }
slotmap = "1.0.6"
grid = { version = "0.11.0", optional = true }

[features]
default = ["std", "grid"]
grid = ["dep:grid"]
alloc = []
std = ["num-traits/std"]
serde = ["dep:serde"]
random = ["dep:rand"]
debug = []

[dev-dependencies]
criterion = "0.4"
rstest = "0.16.0"
rand = "0.8.5"
rand_chacha = "0.3.1"

# Enable example and test-specific features
taffy = { path = ".", features = ["random"] }

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "generated"
path = "benches/generated/mod.rs"
harness = false

[[bench]]
name = "complex"
path = "benches/complex.rs"
harness = false

[[bench]]
name = "big_tree"
path = "benches/big_tree.rs"
harness = false

[workspace]
members = ["scripts/gentest"]
